name: WSL Fedora Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v6
      - uses: Vampire/setup-wsl@v7
        with:
          distribution: Ubuntu-18.04
          additional-packages: golang
      - name: Run Go Hello World
        shell: wsl-bash {0}
        run: go run main.go
